import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider, auth } from '@clerk/nextjs'
import { EdgeStoreProvider } from '@/lib/edgestore'
import { Toaster } from '@/components/ui/toaster'
import './globals.css'

import { db } from '@/lib/db'
import { ThemeProvider } from '@/components/providers/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Inst2024',
  description: 'Generated by create next app',
}

async function getData(email: string) {
  if (email) {
    const data = await db.user.findUnique({
      where: {
        email,
      },
      select: {
        colorScheme: true,
      },
    })
    return data
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { sessionClaims } = auth()

  const email = sessionClaims?.email
  const data = await getData(email as string)

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${inter.className} ${data?.colorScheme ?? 'theme-orange'}`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
